### ISSUE TITLE
not finding playlist with my playlist ID

### ISSUE THREAD

**Issue by agutthon777** [justjim1220/MMM-RandomYouTubePlayer#1]
I have installed the module and have found the playlist... the module is reporting it can not find the playlist... i have verified that the playlist is public... what can i be doing wrong?  my playlist ID is PL8xb_PCkykFQkm2kZwY8gUgxX5WULj5C6

Thanks

**Comment by justjim1220** [comment]
Problem fixed
Please run 'git pull && npm install"

Enjoy!
