### ISSUE TITLE
Can't get module working on my Raspberry Pi 3

### ISSUE THREAD

**Issue by 12elax** [justjim1220/MMM-RandomYouTubePlayer#4]
Hi,

this module is exactly what I was looking for. As I just started to get into programming and working with the Pi, I can't get the module to work. Integrating in my config.js file was no problem. The Terminal doesn't return any errors, but apperently the module does nothing.

Ideally I am trying to get the module to play the audio of random videos from a playlist as soon as I push a physical button connected to my RPI.

Help is appreciated! Thanks again for your effort programming this module!
12elax

**Comment by justjim1220** [comment]
Please try again. I found a typo and it has been fixed. Thanks!

**Comment by michael24h** [comment]
Many thanks for helping, 
module show up, when mm starts. but  come up with video unavailable .
im not sure if this is nodule or issue with my mm. (Ubuntu 18.04)
first id: PL7qGDzGn2kiQ8yqYpVtGS7zKvfvhyx5UX
second id: PLBF29177C5D2545EF

Many Thanks

**Comment by justjim1220** [comment]
There are some videos that are blocked by YouTube.

Have you tried to skip it?

**Comment by michael24h** [comment]
Hello 
Thanks for fix.
 At this point module starting and showing up, with no problem.
 Skip to next, working just fine. But module won’t auto play, I tried also add '?autoplay=1', at end of id. 
I also chnge playlist id, with no luck

Thank you

**Comment by justjim1220** [comment]
Yeah, that is another thing I have been working on. it does that sometimes
for me as well.
When I first made it, it worked every time. then here a while back, it
starting to not autoplay or shuffle the playlist.
I think I got the shuffles working, but the autoplay is sporadic.
Stay tuned, I am working on it. 😎

**Comment by michael24h** [comment]
Update:
Just removed “=“ from id playlist
So looks like this.

playlistId: "PL7qGDzGn2kiQ8yqYpVtGS7zKvfvhyx5UX?autoplay1”, 
Still won’t autoplay, but when I pressed skip button then start playing next youtube, with no problem :)
Later on I will, tray to do same think on ubuntu, see if this temporary fix will help

Many Thanks

**Comment by justjim1220** [comment]
If you get it figured out, Please do a pull request.
I know one time I was counting the ratio of when it does autoplay, it was
like 12 to 1. the one being when it actually worked.

**Comment by michael24h** [comment]
Ok
Thanks

**Comment by michael24h** [comment]
One more think.
I change ID playlist to:
playlistId: "PL7qGDzGn2kiQ8yqYpVtGS7zKvfvhyx5UX?autoplay1version=3&loop=1&playlist=PL7qGDzGn2kiQ8yqYpVtGS7zKvfvhyx5UX”,
Works now just fine. Would you please check this fix, I will do for you?

Thanks

**Comment by justjim1220** [comment]
no, that did not work for me. didn't even show the player, and threw an
error.
