### ISSUE TITLE
module is not showing up

### ISSUE THREAD

**Issue by michael24h** [justjim1220/MMM-RandomYouTubePlayer#5]
I installed the module and used your config in config.js. module is not showing up,  as mirror start up just fine.

{
	module: "MMM-RandomYoutubePlayer", 
	position: "top_center",	      // This can be any of the regions...
	config: {
	    playlistId: "PLl_KM23gznEAZW-INW8ty4QNaHH8JCnNW",     // See Configuration Options below...
            height: 480,
            width: 720,
	    }
	},

**Comment by michael24h** [comment]
Help much appreciated 
Many thanks  for your time and effort with programming this module

**Comment by weiserhei** [comment]
The same for me, just adding some Debug Information from the MM Output:

![2019-01-24-050831_1280x1024_scrot2](https://user-images.githubusercontent.com/7581732/51654137-bdb7b700-1f96-11e9-92fd-7f757ad671f3.png)

System is RPI3B, latest Raspbian and MagicMirror.

**Comment by justjim1220** [comment]
at this point, I am not sure why this is not working anymore.
I apologize for the inconvenience, I am working on it to figure it out.
Thank you for your patience!

**Comment by justjim1220** [comment]
@weiserhei 
May I ask what you placed within the code to get the error to show up?
I am not getting any errors, but the module still doesn't show up on my end.

**Comment by justjim1220** [comment]
OK, I found the issue...
typo in the README: module:` "MMM-RandomYoutubePlayer", ` should be `module: "MMM-RandomYouTubePlayer", `
`{
	module: "MMM-RandomYouTubePlayer", 
	position: "top_center",	      // This can be any of the regions...
	config: {
	    playlistId: "PLl_KM23gznEAZW-INW8ty4QNaHH8JCnNW",     // See Configuration Options below...
            height: 480,
            width: 720,
	    }
	},`
Apologies for the inconvenience. README has been fixed.

**Comment by weiserhei** [comment]
Starting MagicMirror with `npm start dev` will give you console output. Thanks for fixing will test it soon!
