### ISSUE TITLE
npm ERR! file /home/pi/MagicMirror/modules/MMM-RandomYouTubePlayer/package.json

### ISSUE THREAD

**Issue by KernelTimes** [justjim1220/MMM-RandomYouTubePlayer#6]

**Comment by justjim1220** [comment]
I need more explanation than just a title...

**Comment by KernelTimes** [comment]
when i try installing it throught npm install this error comes

**Comment by justjim1220** [comment]
Apologies, looks like I had an syntax error in the file. 

It is fixed now, try git pull && npm i
